; generated by ylangc 0.3 (ABI 0.3, docs/ylangc.md)

        .import println
        .import println.frame
        .import readstr
        .import readstr.frame
        .import strcmp
        .import strcmp.frame
        .import __stack_top
        .export str
        .export main
        .export main.frame

; start-up code at address 0: set the stack pointer, run the @main function, stop
        .code vector
        .export _start
_start: mova    r14a, =__stack_top     ; SP = the last byte of RAM; the stack grows down
        brl     r12a, =main               ; call main
.l spin:
        br      .b =spin               ; main returned: stop here

        .code

; ------------------------------------------------------------------------------
; echo: fn()
; ------------------------------------------------------------------------------
        .addr   =echo.frame            ; header: the frame of echo ...
        .dword  6                      ; ... and its size
echo:
        str     r12, =echo.frame       ; save the return address
        str     r13, =echo.frame+1
; line 13: loop {
echo.2:                                 ; loop
; line 14: readstr(@ptr(str));
        mova    r10a, =str             ; r10a = @ptr(str)
        mov     r0, r10
        mov     r1, r11
        str     r0, =echo.frame+2      ; spill @ptr(str) (byte 0)
        str     r1, =echo.frame+3      ; spill @ptr(str) (byte 1)
        ldr     r0, =echo.frame+2      ; reload @ptr(str) (byte 0)
        ldr     r1, =echo.frame+3      ; reload @ptr(str) (byte 1)
        str     r0, =readstr.frame     ; argument 1 of readstr (byte 0) = r0
        str     r1, =readstr.frame+1   ; argument 1 of readstr (byte 1) = r1
        brl     r12a, =readstr         ; call readstr(@ptr(str))
; line 15: if (strcmp(@ptr(str), s"") eq 0) {
        mova    r10a, =str             ; r10a = @ptr(str)
        mov     r0, r10
        mov     r1, r11
        mova    r10a, =str.1           ; r10a = address of s""
        mov     r2, r10
        mov     r3, r11
        str     r0, =echo.frame+2      ; spill @ptr(str) (byte 0)
        str     r1, =echo.frame+3      ; spill @ptr(str) (byte 1)
        str     r2, =echo.frame+4      ; spill s"" (byte 0)
        str     r3, =echo.frame+5      ; spill s"" (byte 1)
        ldr     r0, =echo.frame+2      ; reload @ptr(str) (byte 0)
        ldr     r1, =echo.frame+3      ; reload @ptr(str) (byte 1)
        str     r0, =strcmp.frame+1    ; argument 1 of strcmp (byte 0) = r0
        str     r1, =strcmp.frame+2    ; argument 1 of strcmp (byte 1) = r1
        ldr     r2, =echo.frame+4      ; reload s"" (byte 0)
        ldr     r3, =echo.frame+5      ; reload s"" (byte 1)
        str     r2, =strcmp.frame+3    ; argument 2 of strcmp (byte 0) = r2
        str     r3, =strcmp.frame+4    ; argument 2 of strcmp (byte 1) = r3
        brl     r12a, =strcmp          ; call strcmp(@ptr(str), s"")
        ldr     r0, =strcmp.frame      ; r0 = result of strcmp
        cmp     r0, #0                 ; flags = strcmp(@ptr(str), s"") - 0
        br.eq   =echo.4                ; if strcmp(@ptr(str), s"") eq 0
        br      =echo.5                ; otherwise
echo.4:                                 ; then: strcmp(@ptr(str), s"") eq 0
; line 16: break;
        br      =echo.3                ; break
        br      =echo.6                ; skip the else part
echo.5:                                 ; not: strcmp(@ptr(str), s"") eq 0
echo.6:                                 ; end of if
; line 18: println(@ptr(str));
        mova    r10a, =str             ; r10a = @ptr(str)
        mov     r0, r10
        mov     r1, r11
        str     r0, =echo.frame+4      ; spill @ptr(str) (byte 0)
        str     r1, =echo.frame+5      ; spill @ptr(str) (byte 1)
        ldr     r0, =echo.frame+4      ; reload @ptr(str) (byte 0)
        ldr     r1, =echo.frame+5      ; reload @ptr(str) (byte 1)
        str     r0, =println.frame     ; argument 1 of println (byte 0) = r0
        str     r1, =println.frame+1   ; argument 1 of println (byte 1) = r1
        brl     r12a, =println         ; call println(@ptr(str))
        br      =echo.2                ; again
echo.3:                                 ; end of loop
echo.1:                                 ; return
        ldr     r12, =echo.frame       ; reload the return address
        ldr     r13, =echo.frame+1
        br      r12a                   ; back to the caller

        .code

; ------------------------------------------------------------------------------
; strtou16: fn([*]uint8) returns uint16
; ------------------------------------------------------------------------------
        .addr   =strtou16.frame        ; header: the frame of strtou16 ...
        .dword  13                     ; ... and its size
strtou16:
        str     r12, =strtou16.frame+4 ; save the return address
        str     r13, =strtou16.frame+5
; line 26: var num: uint16 = 0;
        mov     r0, #0                 ; r0 = 0 (byte 0)
        mov     r1, #0                 ; r1 = 0 (byte 1)
        str     r0, =strtou16.frame+6  ; num (byte 0) = r0
        str     r1, =strtou16.frame+7  ; num (byte 1) = r1
; line 27: var i: uint8 = 0;
        mov     r0, #0                 ; r0 = 0
        str     r0, =strtou16.frame+8  ; i = r0
; line 28: loop {
strtou16.2:                             ; loop
; line 29: if (strin[i] eq 0) {
        ldr     r0, =strtou16.frame+2  ; r0 = strin (byte 0)
        ldr     r1, =strtou16.frame+3  ; r1 = strin (byte 1)
        ldr     r2, =strtou16.frame+8  ; r2 = i
        mov     r3, #0                 ; zero extension of i
        adds    r0, r0, r2             ; address of strin[i]
        addc    r1, r1, r3
        mov     r10, r0                ; r10a = address in r1:r0
        mov     r11, r1
        ldo     r2, r10a, #0           ; r2 = strin[i]
        cmp     r2, #0                 ; flags = strin[i] - 0
        br.eq   =strtou16.4            ; if strin[i] eq 0
        br      =strtou16.5            ; otherwise
strtou16.4:                             ; then: strin[i] eq 0
; line 30: break;
        br      =strtou16.3            ; break
        br      =strtou16.6            ; skip the else part
strtou16.5:                             ; not: strin[i] eq 0
strtou16.6:                             ; end of if
; line 32: num = num * 10 + @cast(uint16)(strin[i] - '0');
        ldr     r0, =strtou16.frame+6  ; r0 = num (byte 0)
        ldr     r1, =strtou16.frame+7  ; r1 = num (byte 1)
        mov     r2, #10                ; r2 = 10 (byte 0)
        mov     r3, #0                 ; r3 = 10 (byte 1)
        str     r0, =strtou16.frame+9  ; spill num (byte 0)
        str     r1, =strtou16.frame+10 ; spill num (byte 1)
        str     r2, =strtou16.frame+11 ; spill 10 (byte 0)
        str     r3, =strtou16.frame+12 ; spill 10 (byte 1)
        ldr     r0, =strtou16.frame+9  ; reload num (byte 0)
        ldr     r1, =strtou16.frame+10 ; reload num (byte 1)
        str     r0, =__mul16.frame+2   ; argument 1 of __mul16 (byte 0) = r0
        str     r1, =__mul16.frame+3   ; argument 1 of __mul16 (byte 1) = r1
        ldr     r2, =strtou16.frame+11 ; reload 10 (byte 0)
        ldr     r3, =strtou16.frame+12 ; reload 10 (byte 1)
        str     r2, =__mul16.frame+4   ; argument 2 of __mul16 (byte 0) = r2
        str     r3, =__mul16.frame+5   ; argument 2 of __mul16 (byte 1) = r3
        brl     r12a, =__mul16         ; call num * 10
        ldr     r0, =__mul16.frame     ; r0 = result of __mul16 (byte 0)
        ldr     r1, =__mul16.frame+1   ; r1 = result of __mul16 (byte 1)
        ldr     r2, =strtou16.frame+2  ; r2 = strin (byte 0)
        ldr     r3, =strtou16.frame+3  ; r3 = strin (byte 1)
        ldr     r4, =strtou16.frame+8  ; r4 = i
        mov     r5, #0                 ; zero extension of i
        adds    r2, r2, r4             ; address of strin[i]
        addc    r3, r3, r5
        mov     r10, r2                ; r10a = address in r3:r2
        mov     r11, r3
        ldo     r4, r10a, #0           ; r4 = strin[i]
        sub     r4, r4, #48            ; strin[i] - 48
        mov     r2, #0                 ; zero extension of strin[i] - 48
        adds    r0, r0, r4             ; (num * 10) + @cast(uint16)(strin[i] -..., byte 0
        addc    r1, r1, r2             ; ... byte 1 with carry
        str     r0, =strtou16.frame+6  ; num (byte 0) = r0
        str     r1, =strtou16.frame+7  ; num (byte 1) = r1
; line 34: i += 1;
        ldr     r0, =strtou16.frame+8  ; r0 = i
        add     r0, r0, #1             ; i + 1
        str     r0, =strtou16.frame+8  ; i = r0
        br      =strtou16.2            ; again
strtou16.3:                             ; end of loop
; line 36: return num;
        ldr     r0, =strtou16.frame+6  ; r0 = num (byte 0)
        ldr     r1, =strtou16.frame+7  ; r1 = num (byte 1)
        str     r0, =strtou16.frame    ; result (byte 0) = r0
        str     r1, =strtou16.frame+1  ; result (byte 1) = r1
        br      =strtou16.1            ; return
strtou16.1:                             ; return
        ldr     r12, =strtou16.frame+4 ; reload the return address
        ldr     r13, =strtou16.frame+5
        br      r12a                   ; back to the caller

        .code

; ------------------------------------------------------------------------------
; u16tostr: fn(uint16, [*]uint8)
; ------------------------------------------------------------------------------
        .addr   =u16tostr.frame        ; header: the frame of u16tostr ...
        .dword  20                     ; ... and its size
u16tostr:
        str     r12, =u16tostr.frame+4 ; save the return address
        str     r13, =u16tostr.frame+5
; line 41: var i: uint16 = 0;
        mov     r0, #0                 ; r0 = 0 (byte 0)
        mov     r1, #0                 ; r1 = 0 (byte 1)
        str     r0, =u16tostr.frame+6  ; i (byte 0) = r0
        str     r1, =u16tostr.frame+7  ; i (byte 1) = r1
; line 42: loop {
u16tostr.2:                             ; loop
; line 43: strout[i] = '0' + @cast(char)(num % 10);
        mov     r0, #48                ; r0 = 48
        ldr     r1, =u16tostr.frame    ; r1 = num (byte 0)
        ldr     r2, =u16tostr.frame+1  ; r2 = num (byte 1)
        mov     r3, #10                ; r3 = 10 (byte 0)
        mov     r4, #0                 ; r4 = 10 (byte 1)
        str     r0, =u16tostr.frame+8  ; spill 48
        str     r1, =u16tostr.frame+9  ; spill num (byte 0)
        str     r2, =u16tostr.frame+10 ; spill num (byte 1)
        str     r3, =u16tostr.frame+11 ; spill 10 (byte 0)
        str     r4, =u16tostr.frame+12 ; spill 10 (byte 1)
        ldr     r0, =u16tostr.frame+9  ; reload num (byte 0)
        ldr     r1, =u16tostr.frame+10 ; reload num (byte 1)
        str     r0, =__modu16.frame+2  ; argument 1 of __modu16 (byte 0) = r0
        str     r1, =__modu16.frame+3  ; argument 1 of __modu16 (byte 1) = r1
        ldr     r2, =u16tostr.frame+11 ; reload 10 (byte 0)
        ldr     r3, =u16tostr.frame+12 ; reload 10 (byte 1)
        str     r2, =__modu16.frame+4  ; argument 2 of __modu16 (byte 0) = r2
        str     r3, =__modu16.frame+5  ; argument 2 of __modu16 (byte 1) = r3
        brl     r12a, =__modu16        ; call num % 10
        ldr     r0, =__modu16.frame    ; r0 = result of __modu16 (byte 0)
        ldr     r1, =__modu16.frame+1  ; r1 = result of __modu16 (byte 1)
        ldr     r1, =u16tostr.frame+8  ; reload 48
        add     r1, r1, r0             ; 48 + @cast(uint8)(num % 10)
        ldr     r0, =u16tostr.frame+2  ; r0 = strout (byte 0)
        ldr     r2, =u16tostr.frame+3  ; r2 = strout (byte 1)
        ldr     r3, =u16tostr.frame+6  ; r3 = i (byte 0)
        ldr     r4, =u16tostr.frame+7  ; r4 = i (byte 1)
        adds    r0, r0, r3             ; address of strout[i]
        addc    r2, r2, r4
        mov     r10, r0                ; r10a = address in r2:r0
        mov     r11, r2
        sto     r1, r10a, #0           ; strout[i] = r1
; line 44: num /= 10;
        ldr     r0, =u16tostr.frame    ; r0 = num (byte 0)
        ldr     r1, =u16tostr.frame+1  ; r1 = num (byte 1)
        mov     r2, #10                ; r2 = 10 (byte 0)
        mov     r3, #0                 ; r3 = 10 (byte 1)
        str     r0, =u16tostr.frame+11 ; spill num (byte 0)
        str     r1, =u16tostr.frame+12 ; spill num (byte 1)
        str     r2, =u16tostr.frame+9  ; spill 10 (byte 0)
        str     r3, =u16tostr.frame+10 ; spill 10 (byte 1)
        ldr     r0, =u16tostr.frame+11 ; reload num (byte 0)
        ldr     r1, =u16tostr.frame+12 ; reload num (byte 1)
        str     r0, =__divu16.frame+2  ; argument 1 of __divu16 (byte 0) = r0
        str     r1, =__divu16.frame+3  ; argument 1 of __divu16 (byte 1) = r1
        ldr     r2, =u16tostr.frame+9  ; reload 10 (byte 0)
        ldr     r3, =u16tostr.frame+10 ; reload 10 (byte 1)
        str     r2, =__divu16.frame+4  ; argument 2 of __divu16 (byte 0) = r2
        str     r3, =__divu16.frame+5  ; argument 2 of __divu16 (byte 1) = r3
        brl     r12a, =__divu16        ; call num / 10
        ldr     r0, =__divu16.frame    ; r0 = result of __divu16 (byte 0)
        ldr     r1, =__divu16.frame+1  ; r1 = result of __divu16 (byte 1)
        str     r0, =u16tostr.frame    ; num (byte 0) = r0
        str     r1, =u16tostr.frame+1  ; num (byte 1) = r1
; line 45: i += 1;
        ldr     r0, =u16tostr.frame+6  ; r0 = i (byte 0)
        ldr     r1, =u16tostr.frame+7  ; r1 = i (byte 1)
        adds    r0, r0, #1             ; i + 1, byte 0
        addc    r1, r1, #0             ; ... byte 1 with carry
        str     r0, =u16tostr.frame+6  ; i (byte 0) = r0
        str     r1, =u16tostr.frame+7  ; i (byte 1) = r1
; line 46: if (num eq 0) {
        ldr     r0, =u16tostr.frame    ; r0 = num (byte 0)
        ldr     r1, =u16tostr.frame+1  ; r1 = num (byte 1)
        eor     r0, r0, #0             ; byte 0: 0 where num and 0 agree
        eor     r1, r1, #0             ; byte 1: 0 where num and 0 agree
        ord     r0, r1                 ; Z = all bytes equal
        br.eq   =u16tostr.4            ; if num eq 0
        br      =u16tostr.5            ; otherwise
u16tostr.4:                             ; then: num eq 0
; line 47: break;
        br      =u16tostr.3            ; break
        br      =u16tostr.6            ; skip the else part
u16tostr.5:                             ; not: num eq 0
u16tostr.6:                             ; end of if
        br      =u16tostr.2            ; again
u16tostr.3:                             ; end of loop
; line 50: strout[i] = 0;
        mov     r0, #0                 ; r0 = 0
        ldr     r1, =u16tostr.frame+2  ; r1 = strout (byte 0)
        ldr     r2, =u16tostr.frame+3  ; r2 = strout (byte 1)
        ldr     r3, =u16tostr.frame+6  ; r3 = i (byte 0)
        ldr     r4, =u16tostr.frame+7  ; r4 = i (byte 1)
        adds    r1, r1, r3             ; address of strout[i]
        addc    r2, r2, r4
        mov     r10, r1                ; r10a = address in r2:r1
        mov     r11, r2
        sto     r0, r10a, #0           ; strout[i] = r0
; line 53: var len: uint16 = i;
        ldr     r0, =u16tostr.frame+6  ; r0 = i (byte 0)
        ldr     r1, =u16tostr.frame+7  ; r1 = i (byte 1)
        str     r0, =u16tostr.frame+13 ; len (byte 0) = r0
        str     r1, =u16tostr.frame+14 ; len (byte 1) = r1
; line 54: var j: uint16 = 0;
        mov     r0, #0                 ; r0 = 0 (byte 0)
        mov     r1, #0                 ; r1 = 0 (byte 1)
        str     r0, =u16tostr.frame+15 ; j (byte 0) = r0
        str     r1, =u16tostr.frame+16 ; j (byte 1) = r1
; line 55: loop {
u16tostr.7:                             ; loop
; line 56: if (j eq len / 2) {
        ldr     r0, =u16tostr.frame+15 ; r0 = j (byte 0)
        ldr     r1, =u16tostr.frame+16 ; r1 = j (byte 1)
        ldr     r2, =u16tostr.frame+13 ; r2 = len (byte 0)
        ldr     r3, =u16tostr.frame+14 ; r3 = len (byte 1)
        mov     r4, #2                 ; r4 = 2 (byte 0)
        mov     r5, #0                 ; r5 = 2 (byte 1)
        str     r0, =u16tostr.frame+9  ; spill j (byte 0)
        str     r1, =u16tostr.frame+10 ; spill j (byte 1)
        str     r2, =u16tostr.frame+11 ; spill len (byte 0)
        str     r3, =u16tostr.frame+12 ; spill len (byte 1)
        str     r4, =u16tostr.frame+17 ; spill 2 (byte 0)
        str     r5, =u16tostr.frame+18 ; spill 2 (byte 1)
        ldr     r0, =u16tostr.frame+11 ; reload len (byte 0)
        ldr     r1, =u16tostr.frame+12 ; reload len (byte 1)
        str     r0, =__divu16.frame+2  ; argument 1 of __divu16 (byte 0) = r0
        str     r1, =__divu16.frame+3  ; argument 1 of __divu16 (byte 1) = r1
        ldr     r2, =u16tostr.frame+17 ; reload 2 (byte 0)
        ldr     r3, =u16tostr.frame+18 ; reload 2 (byte 1)
        str     r2, =__divu16.frame+4  ; argument 2 of __divu16 (byte 0) = r2
        str     r3, =__divu16.frame+5  ; argument 2 of __divu16 (byte 1) = r3
        brl     r12a, =__divu16        ; call len / 2
        ldr     r0, =__divu16.frame    ; r0 = result of __divu16 (byte 0)
        ldr     r1, =__divu16.frame+1  ; r1 = result of __divu16 (byte 1)
        ldr     r2, =u16tostr.frame+9  ; reload j (byte 0)
        ldr     r3, =u16tostr.frame+10 ; reload j (byte 1)
        eor     r2, r2, r0             ; byte 0: 0 where j and len / 2 agree
        eor     r3, r3, r1             ; byte 1: 0 where j and len / 2 agree
        ord     r2, r3                 ; Z = all bytes equal
        br.eq   =u16tostr.9            ; if j eq (len / 2)
        br      =u16tostr.10           ; otherwise
u16tostr.9:                             ; then: j eq (len / 2)
; line 57: break;
        br      =u16tostr.8            ; break
        br      =u16tostr.11           ; skip the else part
u16tostr.10:                            ; not: j eq (len / 2)
u16tostr.11:                            ; end of if
; line 59: var temp: char = strout[j];
        ldr     r0, =u16tostr.frame+2  ; r0 = strout (byte 0)
        ldr     r1, =u16tostr.frame+3  ; r1 = strout (byte 1)
        ldr     r2, =u16tostr.frame+15 ; r2 = j (byte 0)
        ldr     r3, =u16tostr.frame+16 ; r3 = j (byte 1)
        adds    r0, r0, r2             ; address of strout[j]
        addc    r1, r1, r3
        mov     r10, r0                ; r10a = address in r1:r0
        mov     r11, r1
        ldo     r2, r10a, #0           ; r2 = strout[j]
        str     r2, =u16tostr.frame+19 ; temp = r2
; line 60: strout[j] = strout[len - 1 - j];
        ldr     r0, =u16tostr.frame+2  ; r0 = strout (byte 0)
        ldr     r1, =u16tostr.frame+3  ; r1 = strout (byte 1)
        ldr     r2, =u16tostr.frame+13 ; r2 = len (byte 0)
        ldr     r3, =u16tostr.frame+14 ; r3 = len (byte 1)
        subs    r2, r2, #1             ; len - 1, byte 0
        subc    r3, r3, #0             ; ... byte 1 with borrow
        ldr     r4, =u16tostr.frame+15 ; r4 = j (byte 0)
        ldr     r5, =u16tostr.frame+16 ; r5 = j (byte 1)
        subs    r2, r2, r4             ; (len - 1) - j, byte 0
        subc    r3, r3, r5             ; ... byte 1 with borrow
        adds    r0, r0, r2             ; address of strout[(len - 1) - j]
        addc    r1, r1, r3
        mov     r10, r0                ; r10a = address in r1:r0
        mov     r11, r1
        ldo     r2, r10a, #0           ; r2 = strout[(len - 1) - j]
        ldr     r0, =u16tostr.frame+2  ; r0 = strout (byte 0)
        ldr     r1, =u16tostr.frame+3  ; r1 = strout (byte 1)
        ldr     r3, =u16tostr.frame+15 ; r3 = j (byte 0)
        ldr     r4, =u16tostr.frame+16 ; r4 = j (byte 1)
        adds    r0, r0, r3             ; address of strout[j]
        addc    r1, r1, r4
        mov     r10, r0                ; r10a = address in r1:r0
        mov     r11, r1
        sto     r2, r10a, #0           ; strout[j] = r2
; line 61: strout[len - 1 - j] = temp;
        ldr     r0, =u16tostr.frame+19 ; r0 = temp
        ldr     r1, =u16tostr.frame+2  ; r1 = strout (byte 0)
        ldr     r2, =u16tostr.frame+3  ; r2 = strout (byte 1)
        ldr     r3, =u16tostr.frame+13 ; r3 = len (byte 0)
        ldr     r4, =u16tostr.frame+14 ; r4 = len (byte 1)
        subs    r3, r3, #1             ; len - 1, byte 0
        subc    r4, r4, #0             ; ... byte 1 with borrow
        ldr     r5, =u16tostr.frame+15 ; r5 = j (byte 0)
        ldr     r6, =u16tostr.frame+16 ; r6 = j (byte 1)
        subs    r3, r3, r5             ; (len - 1) - j, byte 0
        subc    r4, r4, r6             ; ... byte 1 with borrow
        adds    r1, r1, r3             ; address of strout[(len - 1) - j]
        addc    r2, r2, r4
        mov     r10, r1                ; r10a = address in r2:r1
        mov     r11, r2
        sto     r0, r10a, #0           ; strout[(len - 1) - j] = r0
; line 62: j += 1;
        ldr     r0, =u16tostr.frame+15 ; r0 = j (byte 0)
        ldr     r1, =u16tostr.frame+16 ; r1 = j (byte 1)
        adds    r0, r0, #1             ; j + 1, byte 0
        addc    r1, r1, #0             ; ... byte 1 with carry
        str     r0, =u16tostr.frame+15 ; j (byte 0) = r0
        str     r1, =u16tostr.frame+16 ; j (byte 1) = r1
        br      =u16tostr.7            ; again
u16tostr.8:                             ; end of loop
u16tostr.1:                             ; return
        ldr     r12, =u16tostr.frame+4 ; reload the return address
        ldr     r13, =u16tostr.frame+5
        br      r12a                   ; back to the caller

        .code

; ------------------------------------------------------------------------------
; sum: fn()
; ------------------------------------------------------------------------------
        .addr   =sum.frame             ; header: the frame of sum ...
        .dword  10                     ; ... and its size
sum:
        str     r12, =sum.frame        ; save the return address
        str     r13, =sum.frame+1
; line 68: var suma: uint16 = 0;
        mov     r0, #0                 ; r0 = 0 (byte 0)
        mov     r1, #0                 ; r1 = 0 (byte 1)
        str     r0, =sum.frame+2       ; suma (byte 0) = r0
        str     r1, =sum.frame+3       ; suma (byte 1) = r1
; line 69: loop {
sum.2:                                  ; loop
; line 70: readstr(@ptr(str));
        mova    r10a, =str             ; r10a = @ptr(str)
        mov     r0, r10
        mov     r1, r11
        str     r0, =sum.frame+4       ; spill @ptr(str) (byte 0)
        str     r1, =sum.frame+5       ; spill @ptr(str) (byte 1)
        ldr     r0, =sum.frame+4       ; reload @ptr(str) (byte 0)
        ldr     r1, =sum.frame+5       ; reload @ptr(str) (byte 1)
        str     r0, =readstr.frame     ; argument 1 of readstr (byte 0) = r0
        str     r1, =readstr.frame+1   ; argument 1 of readstr (byte 1) = r1
        brl     r12a, =readstr         ; call readstr(@ptr(str))
; line 71: if (strcmp(@ptr(str), s"") eq 0) {
        mova    r10a, =str             ; r10a = @ptr(str)
        mov     r0, r10
        mov     r1, r11
        mova    r10a, =str.2           ; r10a = address of s""
        mov     r2, r10
        mov     r3, r11
        str     r0, =sum.frame+4       ; spill @ptr(str) (byte 0)
        str     r1, =sum.frame+5       ; spill @ptr(str) (byte 1)
        str     r2, =sum.frame+6       ; spill s"" (byte 0)
        str     r3, =sum.frame+7       ; spill s"" (byte 1)
        ldr     r0, =sum.frame+4       ; reload @ptr(str) (byte 0)
        ldr     r1, =sum.frame+5       ; reload @ptr(str) (byte 1)
        str     r0, =strcmp.frame+1    ; argument 1 of strcmp (byte 0) = r0
        str     r1, =strcmp.frame+2    ; argument 1 of strcmp (byte 1) = r1
        ldr     r2, =sum.frame+6       ; reload s"" (byte 0)
        ldr     r3, =sum.frame+7       ; reload s"" (byte 1)
        str     r2, =strcmp.frame+3    ; argument 2 of strcmp (byte 0) = r2
        str     r3, =strcmp.frame+4    ; argument 2 of strcmp (byte 1) = r3
        brl     r12a, =strcmp          ; call strcmp(@ptr(str), s"")
        ldr     r0, =strcmp.frame      ; r0 = result of strcmp
        cmp     r0, #0                 ; flags = strcmp(@ptr(str), s"") - 0
        br.eq   =sum.4                 ; if strcmp(@ptr(str), s"") eq 0
        br      =sum.5                 ; otherwise
sum.4:                                  ; then: strcmp(@ptr(str), s"") eq 0
; line 72: break;
        br      =sum.3                 ; break
        br      =sum.6                 ; skip the else part
sum.5:                                  ; not: strcmp(@ptr(str), s"") eq 0
sum.6:                                  ; end of if
; line 74: var num: uint16 = strtou16(@ptr(str));
        mova    r10a, =str             ; r10a = @ptr(str)
        mov     r0, r10
        mov     r1, r11
        str     r0, =sum.frame+6       ; spill @ptr(str) (byte 0)
        str     r1, =sum.frame+7       ; spill @ptr(str) (byte 1)
        ldr     r0, =sum.frame+6       ; reload @ptr(str) (byte 0)
        ldr     r1, =sum.frame+7       ; reload @ptr(str) (byte 1)
        str     r0, =strtou16.frame+2  ; argument 1 of strtou16 (byte 0) = r0
        str     r1, =strtou16.frame+3  ; argument 1 of strtou16 (byte 1) = r1
        brl     r12a, =strtou16        ; call strtou16(@ptr(str))
        ldr     r0, =strtou16.frame    ; r0 = result of strtou16 (byte 0)
        ldr     r1, =strtou16.frame+1  ; r1 = result of strtou16 (byte 1)
        str     r0, =sum.frame+8       ; num (byte 0) = r0
        str     r1, =sum.frame+9       ; num (byte 1) = r1
; line 75: suma += num;
        ldr     r0, =sum.frame+2       ; r0 = suma (byte 0)
        ldr     r1, =sum.frame+3       ; r1 = suma (byte 1)
        ldr     r2, =sum.frame+8       ; r2 = num (byte 0)
        ldr     r3, =sum.frame+9       ; r3 = num (byte 1)
        adds    r0, r0, r2             ; suma + num, byte 0
        addc    r1, r1, r3             ; ... byte 1 with carry
        str     r0, =sum.frame+2       ; suma (byte 0) = r0
        str     r1, =sum.frame+3       ; suma (byte 1) = r1
        br      =sum.2                 ; again
sum.3:                                  ; end of loop
; line 79: u16tostr(suma, @ptr(str));
        ldr     r0, =sum.frame+2       ; r0 = suma (byte 0)
        ldr     r1, =sum.frame+3       ; r1 = suma (byte 1)
        mova    r10a, =str             ; r10a = @ptr(str)
        mov     r2, r10
        mov     r3, r11
        str     r0, =sum.frame+6       ; spill suma (byte 0)
        str     r1, =sum.frame+7       ; spill suma (byte 1)
        str     r2, =sum.frame+4       ; spill @ptr(str) (byte 0)
        str     r3, =sum.frame+5       ; spill @ptr(str) (byte 1)
        ldr     r0, =sum.frame+6       ; reload suma (byte 0)
        ldr     r1, =sum.frame+7       ; reload suma (byte 1)
        str     r0, =u16tostr.frame    ; argument 1 of u16tostr (byte 0) = r0
        str     r1, =u16tostr.frame+1  ; argument 1 of u16tostr (byte 1) = r1
        ldr     r2, =sum.frame+4       ; reload @ptr(str) (byte 0)
        ldr     r3, =sum.frame+5       ; reload @ptr(str) (byte 1)
        str     r2, =u16tostr.frame+2  ; argument 2 of u16tostr (byte 0) = r2
        str     r3, =u16tostr.frame+3  ; argument 2 of u16tostr (byte 1) = r3
        brl     r12a, =u16tostr        ; call u16tostr(suma, @ptr(str))
; line 81: println(@ptr(str));
        mova    r10a, =str             ; r10a = @ptr(str)
        mov     r0, r10
        mov     r1, r11
        str     r0, =sum.frame+4       ; spill @ptr(str) (byte 0)
        str     r1, =sum.frame+5       ; spill @ptr(str) (byte 1)
        ldr     r0, =sum.frame+4       ; reload @ptr(str) (byte 0)
        ldr     r1, =sum.frame+5       ; reload @ptr(str) (byte 1)
        str     r0, =println.frame     ; argument 1 of println (byte 0) = r0
        str     r1, =println.frame+1   ; argument 1 of println (byte 1) = r1
        brl     r12a, =println         ; call println(@ptr(str))
sum.1:                                  ; return
        ldr     r12, =sum.frame        ; reload the return address
        ldr     r13, =sum.frame+1
        br      r12a                   ; back to the caller

        .code

; ------------------------------------------------------------------------------
; recognize_command: fn([*]uint8)
; ------------------------------------------------------------------------------
        .addr   =recognize_command.frame ; header: the frame of recognize_command ...
        .dword  8                      ; ... and its size
recognize_command:
        str     r12, =recognize_command.frame+2 ; save the return address
        str     r13, =recognize_command.frame+3
; line 87: if (strcmp(strin, s"echo") eq 0) {
        ldr     r0, =recognize_command.frame ; r0 = strin (byte 0)
        ldr     r1, =recognize_command.frame+1 ; r1 = strin (byte 1)
        mova    r10a, =str.3           ; r10a = address of s"echo"
        mov     r2, r10
        mov     r3, r11
        str     r0, =recognize_command.frame+4 ; spill strin (byte 0)
        str     r1, =recognize_command.frame+5 ; spill strin (byte 1)
        str     r2, =recognize_command.frame+6 ; spill s"echo" (byte 0)
        str     r3, =recognize_command.frame+7 ; spill s"echo" (byte 1)
        ldr     r0, =recognize_command.frame+4 ; reload strin (byte 0)
        ldr     r1, =recognize_command.frame+5 ; reload strin (byte 1)
        str     r0, =strcmp.frame+1    ; argument 1 of strcmp (byte 0) = r0
        str     r1, =strcmp.frame+2    ; argument 1 of strcmp (byte 1) = r1
        ldr     r2, =recognize_command.frame+6 ; reload s"echo" (byte 0)
        ldr     r3, =recognize_command.frame+7 ; reload s"echo" (byte 1)
        str     r2, =strcmp.frame+3    ; argument 2 of strcmp (byte 0) = r2
        str     r3, =strcmp.frame+4    ; argument 2 of strcmp (byte 1) = r3
        brl     r12a, =strcmp          ; call strcmp(strin, s"echo")
        ldr     r0, =strcmp.frame      ; r0 = result of strcmp
        cmp     r0, #0                 ; flags = strcmp(strin, s"echo") - 0
        br.eq   =recognize_command.2   ; if strcmp(strin, s"echo") eq 0
        br      =recognize_command.3   ; otherwise
recognize_command.2:                    ; then: strcmp(strin, s"echo") eq 0
; line 88: echo();
        brl     r12a, =echo            ; call echo()
        br      =recognize_command.4   ; skip the else part
recognize_command.3:                    ; else
; line 89: } else if (strcmp(strin, s"sum") eq 0) {
        ldr     r0, =recognize_command.frame ; r0 = strin (byte 0)
        ldr     r1, =recognize_command.frame+1 ; r1 = strin (byte 1)
        mova    r10a, =str.4           ; r10a = address of s"sum"
        mov     r2, r10
        mov     r3, r11
        str     r0, =recognize_command.frame+6 ; spill strin (byte 0)
        str     r1, =recognize_command.frame+7 ; spill strin (byte 1)
        str     r2, =recognize_command.frame+4 ; spill s"sum" (byte 0)
        str     r3, =recognize_command.frame+5 ; spill s"sum" (byte 1)
        ldr     r0, =recognize_command.frame+6 ; reload strin (byte 0)
        ldr     r1, =recognize_command.frame+7 ; reload strin (byte 1)
        str     r0, =strcmp.frame+1    ; argument 1 of strcmp (byte 0) = r0
        str     r1, =strcmp.frame+2    ; argument 1 of strcmp (byte 1) = r1
        ldr     r2, =recognize_command.frame+4 ; reload s"sum" (byte 0)
        ldr     r3, =recognize_command.frame+5 ; reload s"sum" (byte 1)
        str     r2, =strcmp.frame+3    ; argument 2 of strcmp (byte 0) = r2
        str     r3, =strcmp.frame+4    ; argument 2 of strcmp (byte 1) = r3
        brl     r12a, =strcmp          ; call strcmp(strin, s"sum")
        ldr     r0, =strcmp.frame      ; r0 = result of strcmp
        cmp     r0, #0                 ; flags = strcmp(strin, s"sum") - 0
        br.eq   =recognize_command.5   ; if strcmp(strin, s"sum") eq 0
        br      =recognize_command.6   ; otherwise
recognize_command.5:                    ; then: strcmp(strin, s"sum") eq 0
; line 90: sum();
        brl     r12a, =sum             ; call sum()
        br      =recognize_command.7   ; skip the else part
recognize_command.6:                    ; not: strcmp(strin, s"sum") eq 0
recognize_command.7:                    ; end of if
recognize_command.4:                    ; end of if
recognize_command.1:                    ; return
        ldr     r12, =recognize_command.frame+2 ; reload the return address
        ldr     r13, =recognize_command.frame+3
        br      r12a                   ; back to the caller

        .code

; ------------------------------------------------------------------------------
; main: fn()
; ------------------------------------------------------------------------------
        .addr   =main.frame            ; header: the frame of main ...
        .dword  4                      ; ... and its size
main:
        str     r12, =main.frame       ; save the return address
        str     r13, =main.frame+1
; line 99: loop {
main.2:                                 ; loop
; line 100: readstr(@ptr(str));
        mova    r10a, =str             ; r10a = @ptr(str)
        mov     r0, r10
        mov     r1, r11
        str     r0, =main.frame+2      ; spill @ptr(str) (byte 0)
        str     r1, =main.frame+3      ; spill @ptr(str) (byte 1)
        ldr     r0, =main.frame+2      ; reload @ptr(str) (byte 0)
        ldr     r1, =main.frame+3      ; reload @ptr(str) (byte 1)
        str     r0, =readstr.frame     ; argument 1 of readstr (byte 0) = r0
        str     r1, =readstr.frame+1   ; argument 1 of readstr (byte 1) = r1
        brl     r12a, =readstr         ; call readstr(@ptr(str))
; line 101: recognize_command(@ptr(str));
        mova    r10a, =str             ; r10a = @ptr(str)
        mov     r0, r10
        mov     r1, r11
        str     r0, =main.frame+2      ; spill @ptr(str) (byte 0)
        str     r1, =main.frame+3      ; spill @ptr(str) (byte 1)
        ldr     r0, =main.frame+2      ; reload @ptr(str) (byte 0)
        ldr     r1, =main.frame+3      ; reload @ptr(str) (byte 1)
        str     r0, =recognize_command.frame ; argument 1 of recognize_command (byte 0) = r0
        str     r1, =recognize_command.frame+1 ; argument 1 of recognize_command (byte 1) = r1
        brl     r12a, =recognize_command ; call recognize_command(@ptr(str))
        br      =main.2                ; again
main.3:                                 ; end of loop
main.1:                                 ; return
        ldr     r12, =main.frame       ; reload the return address
        ldr     r13, =main.frame+1
        br      r12a                   ; back to the caller

        .code

; ------------------------------------------------------------------------------
; __mul16: fn(uint16, uint16) returns uint16
; ------------------------------------------------------------------------------
        .addr   =__mul16.frame         ; header: the frame of __mul16 ...
        .dword  10                     ; ... and its size
__mul16:
        str     r12, =__mul16.frame+6  ; save the return address
        str     r13, =__mul16.frame+7
        mov     r0, #0                 ; r0 = 0 (byte 0)
        mov     r1, #0                 ; r1 = 0 (byte 1)
        str     r0, =__mul16.frame+8   ; r (byte 0) = r0
        str     r1, =__mul16.frame+9   ; r (byte 1) = r1
__mul16.2:                              ; loop
        ldr     r0, =__mul16.frame+4   ; r0 = b (byte 0)
        ldr     r1, =__mul16.frame+5   ; r1 = b (byte 1)
        eor     r0, r0, #0             ; byte 0: 0 where b and 0 agree
        eor     r1, r1, #0             ; byte 1: 0 where b and 0 agree
        ord     r0, r1                 ; Z = all bytes equal
        br.eq   =__mul16.4             ; if b eq 0
        br      =__mul16.5             ; otherwise
__mul16.4:                              ; then: b eq 0
        br      =__mul16.3             ; break
        br      =__mul16.6             ; skip the else part
__mul16.5:                              ; not: b eq 0
__mul16.6:                              ; end of if
        ldr     r0, =__mul16.frame+4   ; r0 = b (byte 0)
        ldr     r1, =__mul16.frame+5   ; r1 = b (byte 1)
        and     r0, r0, #1             ; b & 1 (byte 0)
        and     r1, r1, #0             ; b & 1 (byte 1)
        eor     r0, r0, #0             ; byte 0: 0 where b & 1 and 0 agree
        eor     r1, r1, #0             ; byte 1: 0 where b & 1 and 0 agree
        ord     r0, r1                 ; Z = all bytes equal
        br.ne   =__mul16.7             ; if (b & 1) ne 0
        br      =__mul16.8             ; otherwise
__mul16.7:                              ; then: (b & 1) ne 0
        ldr     r0, =__mul16.frame+8   ; r0 = r (byte 0)
        ldr     r1, =__mul16.frame+9   ; r1 = r (byte 1)
        ldr     r2, =__mul16.frame+2   ; r2 = a (byte 0)
        ldr     r3, =__mul16.frame+3   ; r3 = a (byte 1)
        adds    r0, r0, r2             ; r + a, byte 0
        addc    r1, r1, r3             ; ... byte 1 with carry
        str     r0, =__mul16.frame+8   ; r (byte 0) = r0
        str     r1, =__mul16.frame+9   ; r (byte 1) = r1
        br      =__mul16.9             ; skip the else part
__mul16.8:                              ; not: (b & 1) ne 0
__mul16.9:                              ; end of if
        ldr     r0, =__mul16.frame+2   ; r0 = a (byte 0)
        ldr     r1, =__mul16.frame+3   ; r1 = a (byte 1)
        lsls    r0, r0                 ; a shl 1: step 1 of 1
        csl     r1, r1                 ; ... carry into byte 1
        str     r0, =__mul16.frame+2   ; a (byte 0) = r0
        str     r1, =__mul16.frame+3   ; a (byte 1) = r1
        ldr     r0, =__mul16.frame+4   ; r0 = b (byte 0)
        ldr     r1, =__mul16.frame+5   ; r1 = b (byte 1)
        lsrs    r1, r1                 ; b shr 1: step 1 of 1
        csr     r0, r0                 ; ... carry into byte 0
        str     r0, =__mul16.frame+4   ; b (byte 0) = r0
        str     r1, =__mul16.frame+5   ; b (byte 1) = r1
        br      =__mul16.2             ; again
__mul16.3:                              ; end of loop
        ldr     r0, =__mul16.frame+8   ; r0 = r (byte 0)
        ldr     r1, =__mul16.frame+9   ; r1 = r (byte 1)
        str     r0, =__mul16.frame     ; result (byte 0) = r0
        str     r1, =__mul16.frame+1   ; result (byte 1) = r1
        br      =__mul16.1             ; return
__mul16.1:                              ; return
        ldr     r12, =__mul16.frame+6  ; reload the return address
        ldr     r13, =__mul16.frame+7
        br      r12a                   ; back to the caller

        .code

; ------------------------------------------------------------------------------
; __divu16: fn(uint16, uint16) returns uint16
; ------------------------------------------------------------------------------
        .addr   =__divu16.frame        ; header: the frame of __divu16 ...
        .dword  13                     ; ... and its size
__divu16:
        str     r12, =__divu16.frame+6 ; save the return address
        str     r13, =__divu16.frame+7
        mov     r0, #0                 ; r0 = 0 (byte 0)
        mov     r1, #0                 ; r1 = 0 (byte 1)
        str     r0, =__divu16.frame+8  ; q (byte 0) = r0
        str     r1, =__divu16.frame+9  ; q (byte 1) = r1
        mov     r0, #0                 ; r0 = 0 (byte 0)
        mov     r1, #0                 ; r1 = 0 (byte 1)
        str     r0, =__divu16.frame+10 ; r (byte 0) = r0
        str     r1, =__divu16.frame+11 ; r (byte 1) = r1
        mov     r0, #16                ; r0 = 16
        str     r0, =__divu16.frame+12 ; i = r0
__divu16.2:                             ; loop
        ldr     r0, =__divu16.frame+12 ; r0 = i
        cmp     r0, #0                 ; flags = i - 0
        br.eq   =__divu16.4            ; if i eq 0
        br      =__divu16.5            ; otherwise
__divu16.4:                             ; then: i eq 0
        br      =__divu16.3            ; break
        br      =__divu16.6            ; skip the else part
__divu16.5:                             ; not: i eq 0
__divu16.6:                             ; end of if
        ldr     r0, =__divu16.frame+10 ; r0 = r (byte 0)
        ldr     r1, =__divu16.frame+11 ; r1 = r (byte 1)
        lsls    r0, r0                 ; r shl 1: step 1 of 1
        csl     r1, r1                 ; ... carry into byte 1
        ldr     r2, =__divu16.frame+2  ; r2 = a (byte 0)
        ldr     r3, =__divu16.frame+3  ; r3 = a (byte 1)
        mov     r4, #15                ; r4 = shift count
__divu16.7:                             ; shift loop: a shr 15
        cmp     r4, #0                 ; count left?
        br.eq   =__divu16.8            ; no: done
        lsrs    r3, r3                 ; shr by one bit
        csr     r2, r2                 ; ... carry into byte 0
        sub     r4, r4, #1             ; count - 1
        br      =__divu16.7
__divu16.8:
        or      r0, r0, r2             ; (r shl 1) | (a shr 15) (byte 0)
        or      r1, r1, r3             ; (r shl 1) | (a shr 15) (byte 1)
        str     r0, =__divu16.frame+10 ; r (byte 0) = r0
        str     r1, =__divu16.frame+11 ; r (byte 1) = r1
        ldr     r0, =__divu16.frame+2  ; r0 = a (byte 0)
        ldr     r1, =__divu16.frame+3  ; r1 = a (byte 1)
        lsls    r0, r0                 ; a shl 1: step 1 of 1
        csl     r1, r1                 ; ... carry into byte 1
        str     r0, =__divu16.frame+2  ; a (byte 0) = r0
        str     r1, =__divu16.frame+3  ; a (byte 1) = r1
        ldr     r0, =__divu16.frame+8  ; r0 = q (byte 0)
        ldr     r1, =__divu16.frame+9  ; r1 = q (byte 1)
        lsls    r0, r0                 ; q shl 1: step 1 of 1
        csl     r1, r1                 ; ... carry into byte 1
        str     r0, =__divu16.frame+8  ; q (byte 0) = r0
        str     r1, =__divu16.frame+9  ; q (byte 1) = r1
        ldr     r0, =__divu16.frame+10 ; r0 = r (byte 0)
        ldr     r1, =__divu16.frame+11 ; r1 = r (byte 1)
        ldr     r2, =__divu16.frame+4  ; r2 = b (byte 0)
        ldr     r3, =__divu16.frame+5  ; r3 = b (byte 1)
        cmp     r0, r2                 ; flags = r - b, byte 0
        subcd   r1, r3                 ; ... byte 1 with borrow
        br.geu  =__divu16.9            ; if r ge b
        br      =__divu16.10           ; otherwise
__divu16.9:                             ; then: r ge b
        ldr     r0, =__divu16.frame+10 ; r0 = r (byte 0)
        ldr     r1, =__divu16.frame+11 ; r1 = r (byte 1)
        ldr     r2, =__divu16.frame+4  ; r2 = b (byte 0)
        ldr     r3, =__divu16.frame+5  ; r3 = b (byte 1)
        subs    r0, r0, r2             ; r - b, byte 0
        subc    r1, r1, r3             ; ... byte 1 with borrow
        str     r0, =__divu16.frame+10 ; r (byte 0) = r0
        str     r1, =__divu16.frame+11 ; r (byte 1) = r1
        ldr     r0, =__divu16.frame+8  ; r0 = q (byte 0)
        ldr     r1, =__divu16.frame+9  ; r1 = q (byte 1)
        or      r0, r0, #1             ; q | 1 (byte 0)
        or      r1, r1, #0             ; q | 1 (byte 1)
        str     r0, =__divu16.frame+8  ; q (byte 0) = r0
        str     r1, =__divu16.frame+9  ; q (byte 1) = r1
        br      =__divu16.11           ; skip the else part
__divu16.10:                            ; not: r ge b
__divu16.11:                            ; end of if
        ldr     r0, =__divu16.frame+12 ; r0 = i
        sub     r0, r0, #1             ; i - 1
        str     r0, =__divu16.frame+12 ; i = r0
        br      =__divu16.2            ; again
__divu16.3:                             ; end of loop
        ldr     r0, =__divu16.frame+8  ; r0 = q (byte 0)
        ldr     r1, =__divu16.frame+9  ; r1 = q (byte 1)
        str     r0, =__divu16.frame    ; result (byte 0) = r0
        str     r1, =__divu16.frame+1  ; result (byte 1) = r1
        br      =__divu16.1            ; return
__divu16.1:                             ; return
        ldr     r12, =__divu16.frame+6 ; reload the return address
        ldr     r13, =__divu16.frame+7
        br      r12a                   ; back to the caller

        .code

; ------------------------------------------------------------------------------
; __modu16: fn(uint16, uint16) returns uint16
; ------------------------------------------------------------------------------
        .addr   =__modu16.frame        ; header: the frame of __modu16 ...
        .dword  11                     ; ... and its size
__modu16:
        str     r12, =__modu16.frame+6 ; save the return address
        str     r13, =__modu16.frame+7
        mov     r0, #0                 ; r0 = 0 (byte 0)
        mov     r1, #0                 ; r1 = 0 (byte 1)
        str     r0, =__modu16.frame+8  ; r (byte 0) = r0
        str     r1, =__modu16.frame+9  ; r (byte 1) = r1
        mov     r0, #16                ; r0 = 16
        str     r0, =__modu16.frame+10 ; i = r0
__modu16.2:                             ; loop
        ldr     r0, =__modu16.frame+10 ; r0 = i
        cmp     r0, #0                 ; flags = i - 0
        br.eq   =__modu16.4            ; if i eq 0
        br      =__modu16.5            ; otherwise
__modu16.4:                             ; then: i eq 0
        br      =__modu16.3            ; break
        br      =__modu16.6            ; skip the else part
__modu16.5:                             ; not: i eq 0
__modu16.6:                             ; end of if
        ldr     r0, =__modu16.frame+8  ; r0 = r (byte 0)
        ldr     r1, =__modu16.frame+9  ; r1 = r (byte 1)
        lsls    r0, r0                 ; r shl 1: step 1 of 1
        csl     r1, r1                 ; ... carry into byte 1
        ldr     r2, =__modu16.frame+2  ; r2 = a (byte 0)
        ldr     r3, =__modu16.frame+3  ; r3 = a (byte 1)
        mov     r4, #15                ; r4 = shift count
__modu16.7:                             ; shift loop: a shr 15
        cmp     r4, #0                 ; count left?
        br.eq   =__modu16.8            ; no: done
        lsrs    r3, r3                 ; shr by one bit
        csr     r2, r2                 ; ... carry into byte 0
        sub     r4, r4, #1             ; count - 1
        br      =__modu16.7
__modu16.8:
        or      r0, r0, r2             ; (r shl 1) | (a shr 15) (byte 0)
        or      r1, r1, r3             ; (r shl 1) | (a shr 15) (byte 1)
        str     r0, =__modu16.frame+8  ; r (byte 0) = r0
        str     r1, =__modu16.frame+9  ; r (byte 1) = r1
        ldr     r0, =__modu16.frame+2  ; r0 = a (byte 0)
        ldr     r1, =__modu16.frame+3  ; r1 = a (byte 1)
        lsls    r0, r0                 ; a shl 1: step 1 of 1
        csl     r1, r1                 ; ... carry into byte 1
        str     r0, =__modu16.frame+2  ; a (byte 0) = r0
        str     r1, =__modu16.frame+3  ; a (byte 1) = r1
        ldr     r0, =__modu16.frame+8  ; r0 = r (byte 0)
        ldr     r1, =__modu16.frame+9  ; r1 = r (byte 1)
        ldr     r2, =__modu16.frame+4  ; r2 = b (byte 0)
        ldr     r3, =__modu16.frame+5  ; r3 = b (byte 1)
        cmp     r0, r2                 ; flags = r - b, byte 0
        subcd   r1, r3                 ; ... byte 1 with borrow
        br.geu  =__modu16.9            ; if r ge b
        br      =__modu16.10           ; otherwise
__modu16.9:                             ; then: r ge b
        ldr     r0, =__modu16.frame+8  ; r0 = r (byte 0)
        ldr     r1, =__modu16.frame+9  ; r1 = r (byte 1)
        ldr     r2, =__modu16.frame+4  ; r2 = b (byte 0)
        ldr     r3, =__modu16.frame+5  ; r3 = b (byte 1)
        subs    r0, r0, r2             ; r - b, byte 0
        subc    r1, r1, r3             ; ... byte 1 with borrow
        str     r0, =__modu16.frame+8  ; r (byte 0) = r0
        str     r1, =__modu16.frame+9  ; r (byte 1) = r1
        br      =__modu16.11           ; skip the else part
__modu16.10:                            ; not: r ge b
__modu16.11:                            ; end of if
        ldr     r0, =__modu16.frame+10 ; r0 = i
        sub     r0, r0, #1             ; i - 1
        str     r0, =__modu16.frame+10 ; i = r0
        br      =__modu16.2            ; again
__modu16.3:                             ; end of loop
        ldr     r0, =__modu16.frame+8  ; r0 = r (byte 0)
        ldr     r1, =__modu16.frame+9  ; r1 = r (byte 1)
        str     r0, =__modu16.frame    ; result (byte 0) = r0
        str     r1, =__modu16.frame+1  ; result (byte 1) = r1
        br      =__modu16.1            ; return
__modu16.1:                             ; return
        ldr     r12, =__modu16.frame+6 ; reload the return address
        ldr     r13, =__modu16.frame+7
        br      r12a                   ; back to the caller

        .data
str:
        .byte 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
        .byte 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
        .byte 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
        .byte 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
str.1:
        .byte 0
str.2:
        .byte 0
str.3:
        .byte 101, 99, 104, 111, 0
str.4:
        .byte 115, 117, 109, 0

        .bss

; frame of echo, 6 bytes (ABI 0.3: the caller writes the arguments here)
;   +0    2   saved return address (r12a)
;   +2    2   spill slot
;   +4    2   spill slot
echo.frame:
        .res 6

; frame of strtou16, 13 bytes (ABI 0.3: the caller writes the arguments here)
;   +0    2   result
;   +2    2   strin
;   +4    2   saved return address (r12a)
;   +6    2   num
;   +8    1   i
;   +9    2   spill slot
;   +11   2   spill slot
strtou16.frame:
        .res 13

; frame of u16tostr, 20 bytes (ABI 0.3: the caller writes the arguments here)
;   +0    2   num
;   +2    2   strout
;   +4    2   saved return address (r12a)
;   +6    2   i
;   +8    1   spill slot
;   +9    2   spill slot
;   +11   2   spill slot
;   +13   2   len
;   +15   2   j
;   +17   2   spill slot
;   +19   1   temp
u16tostr.frame:
        .res 20

; frame of sum, 10 bytes (ABI 0.3: the caller writes the arguments here)
;   +0    2   saved return address (r12a)
;   +2    2   suma
;   +4    2   spill slot
;   +6    2   spill slot
;   +8    2   num
sum.frame:
        .res 10

; frame of recognize_command, 8 bytes (ABI 0.3: the caller writes the arguments here)
;   +0    2   strin
;   +2    2   saved return address (r12a)
;   +4    2   spill slot
;   +6    2   spill slot
recognize_command.frame:
        .res 8

; frame of main, 4 bytes (ABI 0.3: the caller writes the arguments here)
;   +0    2   saved return address (r12a)
;   +2    2   spill slot
main.frame:
        .res 4

; frame of __mul16, 10 bytes (ABI 0.3: the caller writes the arguments here)
;   +0    2   result
;   +2    2   a
;   +4    2   b
;   +6    2   saved return address (r12a)
;   +8    2   r
__mul16.frame:
        .res 10

; frame of __divu16, 13 bytes (ABI 0.3: the caller writes the arguments here)
;   +0    2   result
;   +2    2   a
;   +4    2   b
;   +6    2   saved return address (r12a)
;   +8    2   q
;   +10   2   r
;   +12   1   i
__divu16.frame:
        .res 13

; frame of __modu16, 11 bytes (ABI 0.3: the caller writes the arguments here)
;   +0    2   result
;   +2    2   a
;   +4    2   b
;   +6    2   saved return address (r12a)
;   +8    2   r
;   +10   1   i
__modu16.frame:
        .res 11
