; generated by ylangc 0.3 (ABI 0.3, docs/ylangc.md)

        .import uart_getc
        .import uart_getc.frame
        .import uart_putc
        .import uart_putc.frame
        .import __stack_top
        .export a
        .export a.frame
        .export main
        .export main.frame

; start-up code at address 0: set the stack pointer, run the @main function, stop
        .code vector
        .export _start
_start:
        psrw    #0
        mova    r14a, =__stack_top     ; SP = the last byte of RAM; the stack grows down
        brl     r12a, =main               ; call main
.l spin:
        br      .b =spin               ; main returned: stop here

        .code

; ------------------------------------------------------------------------------
; a: fn()
; ------------------------------------------------------------------------------
        .addr   =a.frame               ; header: the frame of a ...
        .dword  2                      ; ... and its size
a:
        str     r12, =a.frame          ; save the return address
        str     r13, =a.frame+1
a.1:                                    ; return
        ldr     r12, =a.frame          ; reload the return address
        ldr     r13, =a.frame+1
        br      r12a                   ; back to the caller

        .code

; ------------------------------------------------------------------------------
; main: fn()
; ------------------------------------------------------------------------------
        .addr   =main.frame            ; header: the frame of main ...
        .dword  4                      ; ... and its size
main:
        str     r12, =main.frame       ; save the return address
        str     r13, =main.frame+1
; line 8: uart_putc('a');
        mov     r0, #97                ; r0 = 97
        str     r0, =main.frame+2      ; spill 97
        ldr     r0, =main.frame+2      ; reload 97
        str     r0, =uart_putc.frame   ; argument 1 of uart_putc = r0
        brl     r12a, =uart_putc       ; call uart_putc(97)
; line 9: loop {
main.2:                                 ; loop
; line 10: var c: char = uart_getc();
        brl     r12a, =uart_getc       ; call uart_getc()
        ldr     r0, =uart_getc.frame   ; r0 = result of uart_getc
        str     r0, =main.frame+3      ; c = r0
; line 11: uart_putc(c);
        ldr     r0, =main.frame+3      ; r0 = c
        str     r0, =main.frame+2      ; spill c
        ldr     r0, =main.frame+2      ; reload c
        str     r0, =uart_putc.frame   ; argument 1 of uart_putc = r0
        brl     r12a, =uart_putc       ; call uart_putc(c)
        br      =main.2                ; again
main.3:                                 ; end of loop
main.1:                                 ; return
        ldr     r12, =main.frame       ; reload the return address
        ldr     r13, =main.frame+1
        br      r12a                   ; back to the caller

        .bss

; frame of a, 2 bytes (ABI 0.3: the caller writes the arguments here)
;   +0    2   saved return address (r12a)
a.frame:
        .res 2

; frame of main, 4 bytes (ABI 0.3: the caller writes the arguments here)
;   +0    2   saved return address (r12a)
;   +2    1   spill slot
;   +3    1   c
main.frame:
        .res 4
